### ISSUE TITLE
Table to Graph Importer CSV example

### ISSUE THREAD

**Issue by karrtikiyer** [memgraph/gqlalchemy#234]
**Memgraph version** 2.6.1

I am trying to reproduce the one to many example shown here: https://memgraph.com/docs/gqlalchemy/how-to-guides/table-to-graph-importer
```one_to_many_relations:
  address: []        # currently needed, leave [] if no relations to define
  individuals:
    - foreign_key: # foreign key used for mapping;
      column_name: add_id         # specifies its column
      reference_table: address    # name of table from which the foreign key is taken
      reference_key: add_id       # column name in reference table from which the foreign key is taken
    label: LIVES_IN        # label applied to relationship created
      from_entity: False     # (optional) define direction of relationship created
```

Can someone please help me with CSV for the same?
Also how should ONE to ONE relationship be specified? Please help.

Thanks in advance.

**Comment by karrtikiyer** [comment]
Also the `-` at the start of `foreign_key` seems to be misplaced in the example of yaml above, can someone help with a proper config file for one to many relationship configuration?

**Comment by katarinasupe** [comment]
Just to add, this is related to [discussion](https://discord.com/channels/842007348272169002/890968055339958292/1092324578140880956) on Discord.

**Comment by karrtikiyer** [comment]
Also logically in the above example of `individuals` & `address`, it is many to one, wherein 1 `individual` can have multiple `addresses`, so shouldn't the foreign key be present in the address table? And so the configuration ```address: [] ``` should have the foreign key to `individual ID`?

**Comment by karrtikiyer** [comment]
Request you to also please provide example for Many to Many Configuration and CSV?
For Many to Many, should the relations be in a separate CSV file? or should we duplicate rows in the referenced table?
E.g. if we have Student to Teacher relation ship, it is many to many, one student can have many teachers and one teacher can have many students. Where should we place the relationship between student and teacher? Should it be placed in a separate CSV file?

**Comment by brunos252** [comment]
Hello @karrtikiyer !
For CSV files you can use the `CSVLocalFileSystemImporter`.
One to one relationships can be defined with the `one_to_many_relations` field. Let me know if you want me to provide an example, but you simply declare the `foreign_key` in the config file.

You are right about the wrong formatting, the proper way to write it would be:
```
one_to_many_relations:
  address: []
  individual:
  - foreign_key:
      column_name: add_id 
      reference_table: address
      reference_key: add_id
    label: LIVES_IN    
```

**Comment by karrtikiyer** [comment]
Thanks @brunos252 , an example of CSV along with corresponding config would help.

**Comment by brunos252** [comment]
For `many_to_many_relations`, the config part would look like:
```
many_to_many_relations:
  incident_individual:
    foreign_key_from:
      column_name: inc_id
      reference_table: incident
      reference_key: inc_id
    foreign_key_to:
      column_name: ind_id
      reference_table: individuals
      reference_key: ind_id
    label: INCIDENT
```

Where you would need to have an associative table (incident_individual.csv) which would contain fields of foreign keys like:
```
inc_id,ind_id,relation
72,23,DRIVER
12,21,PASSENGER
...
```
