### ISSUE TITLE
[Feature Request] Please allow add edge properties in Loaders

### ISSUE THREAD

**Issue by SuperBo** [memgraph/gqlalchemy#301]
**Memgraph version** Which version did you use? v2.13.0

**Environment** Some information about the environment you are using Memgraph
on: operating system, how do you connect, with or without docker, which driver
etc.

**Describe the bug**
Currently, there are no way to add properties to relationship created with "gqlalchemy.transformations.importing.loaders".

Please allow to add properties into created relationships in "many_to_many" cases.

**Expected behavior**

Allow to to add properties as well as column mappers.

```yaml
many_to_many_relations:       # intended to be used in case of associative tables
  example:
    foreign_key_from:        # describes the source of the relationship
      column_name:
      reference_table:
      reference_key:
    foreign_key_to:          # describes the destination of the relationship
      column_name:
      reference_table:
      reference_key:
    label:
    column_names_mapping: {"current_column_name": "mapped_name"}
```

**Logs**
No log

**Additional context**
All properties in associate table should be added to relationship properties.
